-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgw3wt2l9MWS0qeOgg
eDFPg9OaAM7M1M2kGV+BFMt/xO6gCgYIKoZIzj0DAQehRANCAATGjuDYaUoSP4h5
ZYWTg34MqE3qNanRVLNpR/YKBpALoutUR8dpVO7QrkDTcF3EhW9GsFn3sLompmn9
XCjWGGAb
-----END PRIVATE KEY-----